# Change prefix key to Ctrl-g
set-option -g prefix C-g
unbind C-b

# Pane navigation with hjkl (to make it consistent with Vim/Neovim)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Create new windows with `C-g c` and split panes with `C-g %` and `C-g "`
bind c new-window
bind % split-window -h
bind \" split-window -v

# Use colors
set-option -g default-terminal "screen-256color"

set-option -g default-shell /usr/bin/fish


set-option -sg escape-time 10
set-option -g focus-events on
